remote_theme: mmistakes/so-simple-theme
author.name: Alejandro Barreto
site.logo: https://avatars2.githubusercontent.com/u/3143819
author.picture: https://avatars2.githubusercontent.com/u/3143819
site.twitter: alejandro5042
